name: test 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, x64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Replace Variables in Policy Files
        run: >
          mkdir -p build
            # Normalize line endings in dev.config for compatibility
          sed -i 's/\r//' configuration/dev.config
            # Replace variables in XML files located in the 'Policies' folder
          while IFS= read -r line || [ -n "$line" ]; do
          if [[ ! "$line" =~ : ]]; then continue; fi
          IFS=':' read -ra KV <<< "$line"
          key=$(echo "${KV[0]}" | xargs)
          value=$(echo "${KV[1]}" | xargs)
          echo "Replacing {{$key}} with $value"
          find policies -type f -name "*.xml" -exec sed -i "s|{{$key}}|$value|g" {} \;
          done < configuration/dev.config
             # Copy updated files to the build directory
          cp policies/*.xml build/
      - name: Debug Policies
        run: |
          echo "Updated Policies:"
          cat ./build/*.xml
          ls -alrt ./build
          pwd
        shell: bash