name: test 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Debug Config File
        run: cat src/configuration/dev.config
      - name: Replace Variables in Policy Files
        run: >
          mkdir -p build
            # Normalize line endings in dev.config for compatibility
          sed -i 's/\r//' src/configuration/dev.config
            # Replace variables in XML files located in the 'Policies' folder
          while IFS= read -r line || [ -n "$line" ]; do
            if [[ "$line" != *:* ]]; then
              continue
            fi
            IFS=':' read -r key value <<< "$line"
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs) 
            echo "Replacing {{$key}} with $value"
            # Perform replacement in XML files
            find src/policies -type f -name "*.xml" -exec sed -i "s|{{$key}}|$value|g" {} \;
          done < src/configuration/dev.config
      - name: Debug Policies
        run: |
          echo "Updated Policies:"
          cat ./build/src/policies/*.xml
          ls -alrt ./build/src/policies
          pwd
        shell: bash
